 export const skills = [
    { name: 'html' },
    { name: 'css' },
    { name: 'sass' },
    { name: 'less' },
    { name: 'ant' },
    { name: 'mui' },
    { name: 'js' },
    { name: 'ts' },
    { name: 'styleComponents' },
    { name: 'git' },
    { name: 'npm' },
    { name: 'zustand'},
    { name: 'react' },
    { name: 'redux' },
    { name: 'next' },
  ];